### ISSUE TITLE
MVVM의 IPropertyChange 이벤트에 관한 질문

### ISSUE THREAD

**Issue by devxoul** [gyuwon/SwiftMvvmTodoList#1]
MVVM에서 각 속성을 Observable로 구성하는 대신에 IPropertyChange 이벤트를 사용해서 하나의 스트림만 사용하는 이유는 무엇인가요? 값이 바뀐 속성의 이름을 String으로 주고받아서 ViewModel의 값을 꺼내오는 방식보다는, Observable로 정의된 각 속성을 관찰하는 방식이 더 자연스러운 방식이 아닐까 하는 생각이 들었습니다.

**Comment by hardtack** [comment]
이슈 코멘트에서 토론을 하는게 적절할 지 모르지만, 값이 바뀐 속성 이름을 String으로 받는 방식이 Observable로 정의된 각 속성을 관찰하는 방식보다 더 자연스럽습니다.
여러개의 스트림을 동시에 observe하는 것은 비결정론적(Nondeterministic)인 행위입니다. 여기서 결정론적(Deterministic)이란, 특정 시점에 상태를 관찰했을 때, 한가지 상태만 관찰이 되는가를 이야기합니다.
단일스트림을 통해 상태의 변화를 관찰하게되면, 한 시점에는 한가지 상태만을 가지게됩니다. 그러나, 다중스트림을 통해 관찰하게되면 동시에 여러 상태를 가질 수 있는것입니다.

인간의 UI 관찰 형태는 결정론적입니다. 한 디바이스에서 특정 시점에 동시에 두가지 이상의 상태를 가진 뷰를 볼 수 없으니까요. UI 프로그램을 만드는 입장에서, 현실세계를 추상화하여 나타내는 프로그램을 만든다면 현실세계의 모습에 맞게 코드를 작성하는게 더 자연스러운게 아닐까요?

물론, subscribe하는 쓰레드는 모두 main thread이므로 결과적으로는 순서가 정해져 실행이 되어 결정론적이게 됩니다. 비결정론적으로 UI를 표현하는것 자체가 모순이니까요. 하지만 이건 개발자의 컨트롤에서 벗어나는 영역입니다. 스트림에서 명확한 순서를 표현해주어 개발하는 사람의 시야로 가져오는것이 더 바람직하다고 생각합니다.

해당 코드를 좀 더 Swift스러운 코드로 작성한다면 string이 아닌 enum을 사용할 것 같습니다.

``` Swift
enum StateField {
  case complete(Boolean)
  case description(String)
}
...
private let _propertyChanged = PublishSubject<StateField>()
...
```

Swift의 enum은 패턴매칭에 사용할 수 있어 매우 유용합니다.

``` Swift
.subscribe { field in switch {
  case .description(let description):
    ...
  case .complete(let complete):
    ...
}}
```

**Comment by devxoul** [comment]
@Hardtack 답변 감사합니다. 제 의도가 잘 전달됐는지 살짝 궁금해서 덧붙이자면, 제가 의도한 것은 아래와 같은 방식입니다. 아래 코드에서 하나의 UI는 하나의 스트림만을 관찰합니다.

**ViewModel**

```swift
let description: Observable<String>
let isComplete: Observable<Bool>
```

**View**

```swift
description
  .bindTo(descriptionLabel.rx.text)

isComplete
  .bindTo(completionSwitch.rx.value)
```

**Comment by gyuwon** [comment]
@Hardtack Swift의 `enum`을 더 이해하고 활용하면 더 나은 API가 만들어질 수도 있겠네요. 의견 감사합니다.

**Comment by gyuwon** [comment]
@devxoul 각 속성을 `Observable<>`로 만드는 것은 관찰자 입장에서 개념적으로 나은 점도 있지만 속성이란 관점에서는 부자연스럽습니다.

```swift
self.description = "foo"

let description = viewModel.description
```

```swift
self.description.onNext("foo")

let description : String = ""
viewModel.description.subscribe({ value in description = value }).dispose()
```

뷰의 코드가 장황해지는 면이 있지만 이것은 프레임워크를 만들어 해결하는 편이 더 좋다고 생각합니다.

```swift
descriptionLabel.rx.bind(viewModel, "description")
completionSwitch.rx.bind(viewModel, "isComplete")
```

**Comment by devxoul** [comment]
@gyuwon 그런 관점에서 생각해볼 수 있겠군요. 답변 감사합니다! (다른 이슈에 대해서도요 😃)
