### ISSUE TITLE
셀 내부에서 발생된 이벤트가 밖으로 전파되는 과정

### ISSUE THREAD

**Issue by devxoul** [gyuwon/SwiftMvvmTodoList#2]
`isCompleted`를 구현하실 때 `UITableViewCell` 안에 `UIButton`을 만들어서 `isCompleted` 값을 토글하는 방식을 부탁드려도 될까요? 셀 내부에서 발생된 메시지가 밖으로 전파되는 과정이 궁금합니다.

`NewTodoItemFormViewModel`에서 `TodoItemListViewModel` 인스턴스에 대한 참조를 가지고 있는 것과 같이, 각각의 `TodoItemListViewModel`이 `TodoItemListViewModel` 인스턴스를 참조하도록 리팩토링 할 계획이신지요?

**Comment by gyuwon** [comment]
@devxoul 아직 구체적으로 생각해보지 않았습니다만 말씀하신 방법을 고려해보겠습니다.
