### ISSUE TITLE
NewTodoItemFormViewModel은 싱글톤인가요?

### ISSUE THREAD

**Issue by devxoul** [gyuwon/SwiftMvvmTodoList#3]
`NewTodoItemFormViewModel`은 최초 1회 만들어져서 계속 재활용되는 것인가요? 매번 다시 만드는 대신에 싱글톤으로 구성하게 된 배경이 궁금합니다.

**Comment by gyuwon** [comment]
@devxoul 싱글톤은 정확한 표현은 아니고요, `ApplicationModel`과 일대일 관계라고 보는 것이 맞겠습니다. 이 구조에 엄격한 기준이 사용된 것은 아닙니다. 제가 뷰모델을 만들 때엔 입력 양식 뷰가 새로운 페이지가 될지 목록과 동일한 페이지에 보여질 지 결정하지 않은 상태였기 때문에 어떻게 뷰를 구성해도 문제가 되지 않도록 했습니다.
