### ISSUE TITLE
View 테스팅

### ISSUE THREAD

**Issue by devxoul** [gyuwon/SwiftMvvmTodoList#4]
View 레이어는 어떻게 테스트 하실 계획이신가요? 예를 들어, `NewTodoItemFormViewController`의 취소 버튼을 선택했을 때 화면이 닫힌다는 항목은 어떻게 테스트할 것인지가 궁금합니다.

**Comment by gyuwon** [comment]
@devxoul 자동화 테스트를 하지 않거나 UI 테스팅을 할 듯 합니다.
