### ISSUE TITLE
Submit 버튼 선택 후 로딩 표시

### ISSUE THREAD

**Issue by devxoul** [gyuwon/SwiftMvvmTodoList#6]
Submit 버튼을 누르면 네트워크 요청을 통해 항목이 추가되는 상황을 가정해보려고 합니다. 로딩이 완료될 때까지 Submit 버튼 위에 `UIActivityIndicatorView`를 표시하고 싶은데요. Submit 버튼의 활성화 여부는 `submit.canExecute`를 사용해서 설정할 수 있지만, 로딩을 표시하는 경우에는 어떤 방식을 사용하면 좋을까요?

ViewModel에 `isLoading`과 같은 속성을 추가하는 방법을 생각해보았으나, '**View의 니즈**'로 인해 ViewModel에 새로운 속성을 추가하는 것은 '**ViewModel이 View에 대한 지식을 가지게 되는**' 상황이라고 판단됩니다.

**Comment by gyuwon** [comment]
@devxoul 뷰모델은 언제나 뷰의 요구에 의해 설계됩니다. 뷰모델이 뷰에 대한 지식을 가진다는 것은 절대적으로 구분되기도 하지만 어떤 경우는 문맥에 따라 결정되기도 합니다. 또한 `isLoading` 속성은 활동 지시자(뷰)를 추상화한다고 해석될 수 있습니다. 텍스트 입력기(뷰)를 추상화하기 위해 뷰모델이 읽기와 쓰기가 가능한 문자열 속성을 가지는 것과 크게 다르지 않은 것이죠.
